### GET REQUESTS

GET http://localhost:8080/biblioteca/usuarios

<> 2024-02-06T101745.500.json

###
GET http://localhost:8080/biblioteca/prestamos

###
GET http://localhost:8080/biblioteca/usuarios/100

<> 2024-02-06T125334.200.json

###
GET http://localhost:8080/biblioteca/libros

###
GET http://localhost:8080/biblioteca/libros/40

###
GET http://localhost:8080/biblioteca/categorias

### POST REQUESTS

POST http://localhost:8080/biblioteca/usuarios
Content-Type: application/json

{
  "nombre": "Avenido",
  "apellidos": "Si no ",
  "prestamosById": []
}

<> 2024-02-06T125515.200.json
<> 2024-02-06T125437.200.json

###
GET http://localhost:8080/biblioteca/prestamos

<> 2024-02-06T125644.200.json


### PRESTAMOS

POST http://localhost:8080/biblioteca/prestamos
Content-Type: application/json

{
  "idPrestamo": 0,
  "fechaPrestamo": "2023-12-14",
  "libro": {"id": 4},
  "usuario":{"id": 2}
}


### LIBROS

POST http://localhost:8080/biblioteca/libros
Content-Type: application/json

{
  "nombre": "La princesa Prometida",
  "autor": "William King",
  "editorial": "emog",
  "categoria": {"id": 9}
}

### CATEGORIAS


POST http://localhost:8080/biblioteca/categorias
Content-Type: application/json

{
 "categoria": "Ciencia fusión"
}

### USUARIOS

POST http://localhost:8080/biblioteca/usuarios
Content-Type: application/json

{
  "id": 24,
  "nombre": "Vdsf",
  "apellidos": "Mort"
}

### PUT
PUT http://localhost:8080/biblioteca/libros/37
Content-Type: application/json

  {
    "id": 37,
    "nombre": "Libro",
    "autor": "con",
    "editorial": "categoría",
    "categoria": {
      "id": 6,
      "categoria": "Seguridad"
    },
    "prestamos": []
  }